#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

runApplication blockMesh

cp -r 0.orig 3600

#runApplication topoSet
runApplication $(getApplication)
paraFoam -touch -vtk

#------------------------------------------------------------------------------
