#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
file=$WM_PROJECT_PHT53_DIR/src/thermophysicalModels
wclean $file/specieFetc95
wclean $file/solidSpecieFetc95
wclean $file/solidFetc95Thermo
#
file=$FOAM_PHT53_SOLVERS/porousHeatTransfer
wclean $file/porousHeatTransferFoam
wclean $file/nigmatulinGasificationFoam
