#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
#compiling libraries
file=$WM_PROJECT_PHT53_DIR/src/thermophysicalModels
wmake $file/speciePHT53
wmake $file/solidSpeciePHT53
wmake $file/solidPHT53Thermo
#compiling solvers
file=$FOAM_PHT53_SOLVERS/porousHeatTransfer
wmake $file/phtEnthalpyFoam
wmake $file/porousHeatTransferFoam
