#---------------------------------*- sh -*-------------------------------------
export PHT53_PROJECT="OpenFOAM-PHT53IACP"
export WM_PROJECT_PHT53_DIR=$HOME/$WM_PROJECT/$PHT53_PROJECT
export FOAM_PHT53_SOLVERS=$WM_PROJECT_PHT53_DIR/applications/solvers
export FOAM_PHT53_ETC=$WM_PROJECT_PHT53_DIR/etc
export FOAM_PHT53_SRC=$WM_PROJECT_PHT53_DIR/src
export FOAM_PHT53_EXAMPLES=$WM_PROJECT_PHT53_DIR/examples
