#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

runApplication blockMesh

restore0Dir

#runApplication topoSet
runApplication $(getApplication) -noFunctionObjects
paraFoam -touch-all
runApplication postProcess -func singleGraph

#------------------------------------------------------------------------------
